application: eve-paste
version: 2
runtime: go
threadsafe: true
api_version: go1

handlers:
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /fonts
  static_dir: static/fonts
- url: /img
  static_dir: static/img
- url: /.*
  script: _go_app
  secure: always